### ISSUE TITLE
Add Media Galleries to Bottom of Articles

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/cs-news-export#1]
Add gallery shortcode to bottom of body text

**Comment by Sporkyy** [comment]
Because there's only one list of images for an article, this should only be done when there are more than 1 image since the first image will become the featured image.

**Comment by Sporkyy** [comment]
Done. Sometimes they look dumb because it's virtually the same image (cropping diffs) from the summary photo and an in-article photo. But it works.

The aesthetics+functionality, however, aren't anything to write home about. It's bog standard WordPress. The theme doesn't do anything, but we can. Later.
